CREATE OR REPLACE PROCEDURE PRC_INVENTARIOVENTA 
(
  P_ID_PRODUCTO IN NUMBER 
, P_ID_SUCURSAL IN NUMBER 
, P_CANTIDAD IN NUMBER 
, OUT_RESULT OUT NUMBER 
, OUT_DETALLE OUT VARCHAR2 
) AS 
BEGIN
  OUT_RESULT:=0;
  UPDATE TBL_SUCURSALPRODUCTO
  SET CANTIDAD_SUCURSALPRODUCTO=CANTIDAD_SUCURSALPRODUCTO-P_CANTIDAD
  WHERE ID_PRODUCTO=P_ID_PRODUCTO
  AND ID_SUCURSAL=P_ID_SUCURSAL;
  COMMIT;
EXCEPTION
WHEN OTHERS THEN
OUT_RESULT:=-1;
OUT_DETALLE:=SQLERRM;
END PRC_INVENTARIOVENTA;